#+TITLE: Flox Resolver

Resolve Nix packages from flakes and catalogs from a set of requirements.

** Quick Start

#+BEGIN_SRC
Usage: resolver [-h] [--one] [--quiet] [--inputs INPUTS] [--preferences PREFERENCES] --descriptor DESCRIPTOR

Resolve nix package descriptors in flakes

Optional arguments:
  -h, --help                    shows help message and exits
  -v, --version                 prints version information and exits
  -o, --one                     return single resolved entry or `null'
  -q, --quiet                   exit 0 even if no resolutions are found
  -i, --inputs INPUTS           inline JSON or path to JSON file containing flake references [default: "{"nixpkgs":"github:NixOS/nixpkgs","nixpkgs-flox":"github:flox/nixpkgs-flox","floxpkgs":"github:flox/floxpkgs"}"]
  -p, --preferences PREFERENCES inline JSON or path to JSON file containing resolver preferences [default: "{}"]
  -d, --descriptor DESCRIPTOR   inline JSON or path to JSON file containing a package descriptor [required]
#+END_SRC

#+BEGIN_SRC shell
$ ./bin/resolver -i '{"nixpkgs":"github:NixOS/nixpkgs"}' -d '{"name":"hello","version":"2.12.1"}'|jq;
[
  {
    "info": {
      "names": {
        "aarch64-darwin": "hello",
        "aarch64-linux": "hello",
        "x86_64-darwin": "hello",
        "x86_64-linux": "hello"
      },
      "semvers": {
        "aarch64-darwin": "2.12.1",
        "aarch64-linux": "2.12.1",
        "x86_64-darwin": "2.12.1",
        "x86_64-linux": "2.12.1"
      },
      "systems": [
        "aarch64-darwin",
        "x86_64-darwin",
        "aarch64-linux",
        "x86_64-linux"
      ],
      "versions": {
        "aarch64-darwin": "2.12.1",
        "aarch64-linux": "2.12.1",
        "x86_64-darwin": "2.12.1",
        "x86_64-linux": "2.12.1"
      }
    },
    "input": {
      "lastModified": 1686600087,
      "narHash": "sha256-vvKp4tIiKxm9fXh+Ndi6o1KzSuVhscy48/w93YHVL2M=",
      "owner": "NixOS",
      "repo": "nixpkgs",
      "rev": "80a3b4b7de2fa0570904c1e4bea7fda58be60c5d",
      "type": "github"
    },
    "path": [
      "legacyPackages",
      null,
      "hello"
    ],
    "uri": "github:NixOS/nixpkgs/80a3b4b7de2fa0570904c1e4bea7fda58be60c5d#legacyPackages.{{system}}.hello"
  }
]
#+END_SRC


** Descriptors

A /descriptor/ is a set of requirements written by the user describing a
dependency that they need.
This is similar to a search query and is used to filter a larger set of
packages down to a satisfactory set.

The simplest for of descriptor is likely a package name, or an attribute
path to a package.
This resolver features a number of additional filters which may be used to
describe pacakges.

*** Fields

- input :: restricts resolution to the named input.
- name :: matches package =pname=, parsed =name=, or attribute name.
- path :: relative or absolute attribute path to derivation.
- version :: exact match on package =version= or parsed =name=.
- semver :: semantic version range filter.
- flake :: whether to search =packages= and =legacyPackages= outputs.
- catalog :: whether to search =catalog= outputs.
- stability :: catalog stability channel match - implies catalog.

*** Example Descriptors
#+BEGIN_SRC json
{ "name": "hello" }
{ "path": ["legacyPackages", null, "python3Packages", "pip"] }
{ "name": "hello", "version": "2.10.1" }
{ "name": "nodejs", "semver": "^18.16" }
{ "name": "nodejs", "semver": ">=14 <18.16.0 || >18.16.0" }
{ "name": "hello", "input": "nixpkgs" }
{ "name": "hello", "catalog": true }
{ "name": "flox", "flake": false, "stability": "unstable" }
#+END_SRC


** Preferences

These settings control resolution behaviors, particularly priority ordering for
inputs and attribute-set prefixes to search under.

All of these fields are optional, and when left unset fallbacks will be used.

Remember that in addition to these preferences, the resolver carries a second
structure with information about inputs.
In our preferences we may refer to those inputs using their "alias"
or short-name.


** Example Settings

#+BEGIN_SRC json
{
  "inputs": ["nixpkgs", "nixpkgs-flox"],
  "allow": {
    "unfree":   false,
    "broken":   false,
    "licenses": ["MIT" "GPL3"]
  },
  "semver": {
    "preferPreReleases": true
  },
  "prefixes": {
    "nixpkgs":      ["legacyPackages", "packages", "catalog"],
    "nixpkgs-flox": ["catalog", "packages", "legacyPackages"]
  },
  "stabilities": {
    "nixpkgs-flox": ["unstable", "staging", "unstable"]
  }
}
#+END_SRC


** TODO
- [ ] Read Inputs from =flake.lock= and =registry.json=.
- [ ] Parse descriptor strings.
- [ ] Optimize with supplemental database.
- [ ] Optimize resolution by =path=.
- [ ] More sensible =info= structure.
- [ ] Additional tests.
- [ ] Drop unused routines.
- [ ] Multi-threading.
- [ ] Disable =builtins.trace= warnings.
- [ ] Consider how =packages.*.default= is handled.
